mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com/volunteer/uapply.pojo


wx:
  appid:
  secret:
  templateId:
  url: https://api.weixin.qq.com/sns/jscode2session?appid=${wx.appid}&secret=${wx.secret}&grant_type=authorization_code&js_code=

spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    username: root
    password: shumaosha2
    url: jdbc:mysql://localhost:3306/uapply?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  #设置开启热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #true：页面不加载缓存，修改即时生效
---

spring:
  profiles: release
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uapply?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: shumaosha2
  #设置开启热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #true：页面不加载缓存，修改即时生效
---
